apiversion: apps/v1
kind: Deployment
metadata:
   name: web
   Namespace: app
spec:
  replicas: 2
  selector:
    matchlabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: rohanlabacr0my6x.azurecr.io
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet: { path: "/", port: 8080}
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet: { path: "/", port: 8080 }
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests: { cpu: "100m", memory: "128Mi" }
          limits:   { cpu: "500m", memory: "512Mi" }